services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ../../cloud_storage/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=access-key
      - MINIO_ROOT_PASSWORD=secret-key
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    command: ["redis-server", "--requirepass", ""]
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "123456"
    volumes:
      - redis_data:/data


volumes:
  minio_data:
  db-data:
  redis_data:
    driver: local
