services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ../../cloud_storage/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  db-data:
